<?php
include('../game.php');
session_start();
if(!isset($_POST['txtchar']))
{
	header('Location:start.php');
	exit;
	
}
else
{
	$_SESSION['cht']=$_POST['txtchar'];
        $money=getCash();
	if($_POST['txtchar']>$money)
	  { 
	    header('Location:start.php?alertnobalance=1');
	    exit;
	  }
	else
	  {
	    header('Location:test1.php');
	    exit;
	  }
}
?>	